image: node:8.11.4
options:
  max-time: 20
pipelines:
  custom:
    standard:
      - step: &install
          name: Get Dependencies
          caches:
            - node
          script:
            - yarn install
          artifacts:
            - node_modules/**
            - public/**
  default:
    - step: *install
  branches:
    master:
      - step: *install
