image: node:8.11.4
options:
  max-time: 20
pipelines:
  custom:
    standard:
      - step: &install
          name: Get Dependencies
          caches:
            - node
          script:
            - yarn install
          artifacts:
            - node_modules/**
            - public/**
      - parallel: &tests
        - step:
            name: Unit Testing
            script:
              - yarn test
      - step: &github-push
          name: Push to GitHub
          script:
            - git config --global push.default matching
            - git push https://$GITHUB_AUTH@github.com/gfcf14/greendream-redesign.git HEAD:master -f
  default:
    - step: *install
    - parallel: *tests
  branches:
    master:
      - step: *install
      - parallel: *tests
      - step: *github-push
  tags:
    'github-*':
      - step: *install
      - parallel: *tests
      - step: *github-push