version: "3.4"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - ./secret-variables.env
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/greendreamdb.sql:/docker-entrypoint-initdb.d/greendreamdb.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 8000
    environment:
      MYSQL_HOST_IP: mysql
    env_file:
    - ./secret-variables.env
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - mysql
    command: yarn start
  client:
    build: ./client
    environment:
      NODE_PATH: src
    env_file:
      - ./secret-variables.env
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: yarn start