export { default as CodePenLogo } from './codepen.svg';
export { default as CPlusPlusLogo } from './cplusplus.svg';
export { default as CPlusPlusWhiteLogo } from './cplusplus-white.svg';
export { default as CSharpLogo } from './csharp.svg';
export { default as CSharpWhiteLogo } from './csharp-white.svg';
export { default as DeviantArtLogo } from './deviantart.svg';
export { default as FacebookLogo } from './facebook.svg';
export { default as FanfictionLogo } from './fanfiction.svg';
export { default as GithubLogo } from './github.svg';
export { default as HTML5Logo } from './html5.svg';
export { default as HTML5WhiteLogo } from './html5-white.svg';
export { default as JavaLogo } from './java.svg';
export { default as JavaWhiteLogo } from './java-white.svg';
export { default as LinkedinLogo } from './linkedin.svg';
export { default as TwitterLogo } from './twitter.svg';
export { default as VBDotNetLogo } from './vbdotnet.svg';
export { default as VBDotNetWhiteLogo } from './vbdotnet-white.svg';
export { default as YoutubeLogo } from './youtube.svg';

